<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\MethodOptions;

/**
 * @api
 *
 * Is this method side-effect-free (or safe in HTTP parlance), or idempotent,
 * or neither? HTTP based RPC implementation may choose GET verb for safe
 * methods, and PUT verb for idempotent methods instead of the default POST.
 */
enum IdempotencyLevel: int
{
    case IDEMPOTENCY_UNKNOWN = 0;

    /** implies idempotent */
    case NO_SIDE_EFFECTS = 1;

    /** idempotent, but may have side effects */
    case IDEMPOTENT = 2;
}
