<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\ExtensionRangeOptions;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Declaration
{
    /**
     * @param ?int $number The extension number declared within the extension range.
     * @param ?string $fullName The fully-qualified name of the extension field. There must be a leading
     * dot in front of the full name.
     * @param ?string $type The fully-qualified type name of the extension field. Unlike
     * Metadata.type, Declaration.type must have a leading dot for messages
     * and enums.
     * @param ?bool $reserved If true, indicates that the number is reserved in the extension range,
     * and any extension field with the number will fail to compile. Set this
     * when a declared extension field is deleted.
     * @param ?bool $repeated If true, indicates that the extension must be defined as repeated.
     * Otherwise the extension must be defined as optional.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public ?int $number = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $fullName = null,
        #[Reflection\Field(3, Reflection\StringT::T)]
        public ?string $type = null,
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public ?bool $reserved = null,
        #[Reflection\Field(6, Reflection\BoolT::T)]
        public ?bool $repeated = null,
    ) {}
}
