<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\ExtensionRangeOptions;

/**
 * @api
 *
 * The verification state of the extension range.
 */
enum VerificationState: int
{
    /** All the extensions of the range must be declared. */
    case DECLARATION = 0;
    case UNVERIFIED = 1;
}
