<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\EnumDescriptorProto;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Range of reserved numeric values. Reserved values may not be used by
 * entries in the same enum. Reserved ranges may not overlap.
 *
 * Note that this is distinct from DescriptorProto.ReservedRange in that it
 * is inclusive such that it can appropriately represent the entire int32
 * domain.
 */
final readonly class EnumReservedRange
{
    /**
     * @param ?int $start Inclusive.
     * @param ?int $end Inclusive.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public ?int $start = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $end = null,
    ) {}
}
