<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\GeneratedCodeInfo\Annotation;

/**
 * @api
 *
 * Represents the identified object's effect on the element in the original
 * .proto file.
 */
enum Semantic: int
{
    /** There is no effect or the effect is indescribable. */
    case NONE = 0;

    /** The element is set or otherwise mutated. */
    case SET = 1;

    /** An alias to the element is returned. */
    case ALIAS = 2;
}
