<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSetDefaults;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A map from every known edition with a unique set of defaults to its
 * defaults. Not all editions may be contained here.  For a given edition,
 * the defaults at the closest matching edition ordered at or before it should
 * be used.  This field must be in strict ascending order by edition.
 */
final readonly class FeatureSetEditionDefault
{
    /**
     * @param ?\Google\Protobuf\FeatureSet $overridableFeatures Defaults of features that can be overridden in this edition.
     * @param ?\Google\Protobuf\FeatureSet $fixedFeatures Defaults of features that can't be overridden in this edition.
     */
    public function __construct(
        #[Reflection\Field(3, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $edition = null,
        #[Reflection\Field(4, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $overridableFeatures = null,
        #[Reflection\Field(5, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $fixedFeatures = null,
    ) {}
}
