<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FileOptions;

/**
 * @api
 *
 * Generated classes can be optimized for speed or code size.
 */
enum OptimizeMode: int
{
    /** Generate complete code for parsing, serialization, */
    case SPEED = 1;

    /**
     * etc.
     *
     * Use ReflectionOps to implement these methods.
     */
    case CODE_SIZE = 2;

    /** Generate code using MessageLite and the lite runtime. */
    case LITE_RUNTIME = 3;
}
