<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldOptions;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class EditionDefault
{
    /**
     * @param ?string $value Textproto value.
     */
    public function __construct(
        #[Reflection\Field(3, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $edition = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $value = null,
    ) {}
}
