<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldOptions;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Information about the support window of a feature.
 */
final readonly class FeatureSupport
{
    /**
     * @param ?\Google\Protobuf\Edition $editionIntroduced The edition that this feature was first available in.  In editions
     * earlier than this one, the default assigned to EDITION_LEGACY will be
     * used, and proto files will not be able to override it.
     * @param ?\Google\Protobuf\Edition $editionDeprecated The edition this feature becomes deprecated in.  Using this after this
     * edition may trigger warnings.
     * @param ?string $deprecationWarning The deprecation warning text if this feature is used after the edition it
     * was marked deprecated in.
     * @param ?\Google\Protobuf\Edition $editionRemoved The edition this feature is no longer available in.  In editions after
     * this one, the last default assigned will be used, and proto files will
     * not be able to override it.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $editionIntroduced = null,
        #[Reflection\Field(2, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $editionDeprecated = null,
        #[Reflection\Field(3, Reflection\StringT::T)]
        public ?string $deprecationWarning = null,
        #[Reflection\Field(4, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $editionRemoved = null,
    ) {}
}
