<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldOptions;

/**
 * @api
 */
enum JSType: int
{
    /** Use the default type. */
    case JS_NORMAL = 0;

    /** Use JavaScript strings. */
    case JS_STRING = 1;

    /** Use JavaScript numbers. */
    case JS_NUMBER = 2;
}
