<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldOptions;

/**
 * @api
 *
 * This indicates the types of entities that the field may apply to when used
 * as an option. If it is unset, then the field may be freely used as an
 * option on any kind of entity.
 */
enum OptionTargetType: int
{
    case TARGET_TYPE_UNKNOWN = 0;
    case TARGET_TYPE_FILE = 1;
    case TARGET_TYPE_EXTENSION_RANGE = 2;
    case TARGET_TYPE_MESSAGE = 3;
    case TARGET_TYPE_FIELD = 4;
    case TARGET_TYPE_ONEOF = 5;
    case TARGET_TYPE_ENUM = 6;
    case TARGET_TYPE_ENUM_ENTRY = 7;
    case TARGET_TYPE_SERVICE = 8;
    case TARGET_TYPE_METHOD = 9;
}
