<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldOptions;

/**
 * @api
 *
 * If set to RETENTION_SOURCE, the option will be omitted from the binary.
 */
enum OptionRetention: int
{
    case RETENTION_UNKNOWN = 0;
    case RETENTION_RUNTIME = 1;
    case RETENTION_SOURCE = 2;
}
