<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSet;

/**
 * @api
 */
enum EnforceNamingStyle: int
{
    case ENFORCE_NAMING_STYLE_UNKNOWN = 0;
    case STYLE2024 = 1;
    case STYLE_LEGACY = 2;
}
