<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSet;

/**
 * @api
 */
enum FieldPresence: int
{
    case FIELD_PRESENCE_UNKNOWN = 0;
    case EXPLICIT = 1;
    case IMPLICIT = 2;
    case LEGACY_REQUIRED = 3;
}
