<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSet;

/**
 * @api
 */
enum MessageEncoding: int
{
    case MESSAGE_ENCODING_UNKNOWN = 0;
    case LENGTH_PREFIXED = 1;
    case DELIMITED = 2;
}
