<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSet;

/**
 * @api
 */
enum Utf8Validation: int
{
    case UTF8_VALIDATION_UNKNOWN = 0;
    case VERIFY = 2;
    case NONE = 3;
}
