<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldDescriptorProto;

/**
 * @api
 */
enum Label: int
{
    /** 0 is reserved for errors */
    case LABEL_OPTIONAL = 1;
    case LABEL_REPEATED = 3;

    /**
     * The required label is only allowed in google.protobuf.  In proto3 and Editions
     * it's explicitly prohibited.  In Editions, the `field_presence` feature
     * can be used to get this behavior.
     */
    case LABEL_REQUIRED = 2;
}
