<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FieldDescriptorProto;

/**
 * @api
 */
enum Type: int
{
    /**
     * 0 is reserved for errors.
     * Order is weird for historical reasons.
     */
    case TYPE_DOUBLE = 1;
    case TYPE_FLOAT = 2;

    /**
     * Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT64 if
     * negative values are likely.
     */
    case TYPE_INT64 = 3;
    case TYPE_UINT64 = 4;

    /**
     * Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT32 if
     * negative values are likely.
     */
    case TYPE_INT32 = 5;
    case TYPE_FIXED64 = 6;
    case TYPE_FIXED32 = 7;
    case TYPE_BOOL = 8;
    case TYPE_STRING = 9;

    /**
     * Tag-delimited aggregate.
     * Group type is deprecated and not supported after google.protobuf. However, Proto3
     * implementations should still be able to parse the group wire format and
     * treat group fields as unknown fields.  In Editions, the group wire format
     * can be enabled via the `message_encoding` feature.
     */
    case TYPE_GROUP = 10;

    /** Length-delimited aggregate. */
    case TYPE_MESSAGE = 11;

    /** New in version 2. */
    case TYPE_BYTES = 12;
    case TYPE_UINT32 = 13;
    case TYPE_ENUM = 14;
    case TYPE_SFIXED32 = 15;
    case TYPE_SFIXED64 = 16;

    /** Uses ZigZag encoding. */
    case TYPE_SINT32 = 17;

    /** Uses ZigZag encoding. */
    case TYPE_SINT64 = 18;
}
