<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\UninterpretedOption;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The name of the uninterpreted option.  Each string represents a segment in
 * a dot-separated name.  is_extension is true iff a segment represents an
 * extension (denoted with parentheses in options specs in .proto files).
 * E.g.,{ ["foo", false], ["bar.baz", true], ["moo", false] } represents
 * "foo.(bar.baz).moo".
 */
final readonly class NamePart
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $namePart = '',
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $isExtension = false,
    ) {}
}
