<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\DescriptorProto;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ExtensionRange
{
    /**
     * @param ?int $start Inclusive.
     * @param ?int $end Exclusive.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public ?int $start = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $end = null,
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\ExtensionRangeOptions::class))]
        public ?\Google\Protobuf\ExtensionRangeOptions $options = null,
    ) {}
}
