<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\DescriptorProto;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Range of reserved tag numbers. Reserved tag numbers may not be used by
 * fields or extension ranges in the same message. Reserved ranges may
 * not overlap.
 */
final readonly class ReservedRange
{
    /**
     * @param ?int $start Inclusive.
     * @param ?int $end Exclusive.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public ?int $start = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $end = null,
    ) {}
}
