<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\FeatureSet\VisibilityFeature;

/**
 * @api
 */
enum DefaultSymbolVisibility: int
{
    case DEFAULT_SYMBOL_VISIBILITY_UNKNOWN = 0;

    /** Default pre-EDITION_2024, all UNSET visibility are export. */
    case EXPORT_ALL = 1;

    /** All top-level symbols default to export, nested default to local. */
    case EXPORT_TOP_LEVEL = 2;

    /** All symbols default to local. */
    case LOCAL_ALL = 3;

    /**
     * All symbols local by default. Nested types cannot be exported.
     * With special case caveat for message { enum {} reserved 1 to max; }
     * This is the recommended setting for new protos.
     */
    case STRICT = 4;
}
