<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\GeneratedCodeInfo;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Annotation
{
    /**
     * @param list<int> $path Identifies the element in the original source .proto file. This field
     * is formatted the same as SourceCodeInfo.Location.path.
     * @param ?string $sourceFile Identifies the filesystem path to the original source .proto.
     * @param ?int $begin Identifies the starting offset in bytes in the generated code
     * that relates to the identified object.
     * @param ?int $end Identifies the ending offset in bytes in the generated code that
     * relates to the identified object. The end offset should be one past
     * the last relevant byte (so the length of the text = end - begin).
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(Reflection\Int32T::T, true))]
        public array $path = [],
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $sourceFile = null,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public ?int $begin = null,
        #[Reflection\Field(4, Reflection\Int32T::T)]
        public ?int $end = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Google\Protobuf\GeneratedCodeInfo\Annotation\Semantic::class))]
        public ?\Google\Protobuf\GeneratedCodeInfo\Annotation\Semantic $semantic = null,
    ) {}
}
