<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 */

declare(strict_types=1);

\Thesis\Protobuf\Pool\Registry::get()->register(
    new \Thesis\Protobuf\Pool\OnceRegistrar(new \Google\Protobuf\GoogleProtobufDescriptorDescriptorRegistry()),
);
