<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a message type.
 */
final readonly class DescriptorProto
{
    /**
     * @param list<\Google\Protobuf\FieldDescriptorProto> $field
     * @param list<\Google\Protobuf\FieldDescriptorProto> $extension
     * @param list<\Google\Protobuf\DescriptorProto> $nestedType
     * @param list<\Google\Protobuf\EnumDescriptorProto> $enumType
     * @param list<\Google\Protobuf\DescriptorProto\ExtensionRange> $extensionRange
     * @param list<\Google\Protobuf\OneofDescriptorProto> $oneofDecl
     * @param list<\Google\Protobuf\DescriptorProto\ReservedRange> $reservedRange
     * @param list<string> $reservedName Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * @param ?\Google\Protobuf\SymbolVisibility $visibility Support for `export` and `local` keywords on enums.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FieldDescriptorProto::class), false))]
        public array $field = [],
        #[Reflection\Field(6, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FieldDescriptorProto::class), false))]
        public array $extension = [],
        #[Reflection\Field(3, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\DescriptorProto::class), false))]
        public array $nestedType = [],
        #[Reflection\Field(4, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\EnumDescriptorProto::class), false))]
        public array $enumType = [],
        #[Reflection\Field(5, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\DescriptorProto\ExtensionRange::class), false))]
        public array $extensionRange = [],
        #[Reflection\Field(8, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\OneofDescriptorProto::class), false))]
        public array $oneofDecl = [],
        #[Reflection\Field(7, new Reflection\ObjectT(\Google\Protobuf\MessageOptions::class))]
        public ?\Google\Protobuf\MessageOptions $options = null,
        #[Reflection\Field(9, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\DescriptorProto\ReservedRange::class), false))]
        public array $reservedRange = [],
        #[Reflection\Field(10, new Reflection\ListT(Reflection\StringT::T, false))]
        public array $reservedName = [],
        #[Reflection\Field(11, new Reflection\EnumT(\Google\Protobuf\SymbolVisibility::class))]
        public ?\Google\Protobuf\SymbolVisibility $visibility = null,
    ) {}
}
