<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

/**
 * @api
 *
 * The full set of known editions.
 */
enum Edition: int
{
    /** A placeholder for an unknown edition value. */
    case EDITION_UNKNOWN = 0;

    /**
     * A placeholder edition for specifying default behaviors *before* a feature
     * was first introduced.  This is effectively an "infinite past".
     */
    case EDITION_LEGACY = 900;

    /**
     * Legacy syntax "editions".  These pre-date editions, but behave much like
     * distinct editions.  These can't be used to specify the edition of proto
     * files, but feature definitions must supply proto2/proto3 defaults for
     * backwards compatibility.
     */
    case EDITION_PROTO2 = 998;
    case EDITION_PROTO3 = 999;

    /**
     * Editions that have been released.  The specific values are arbitrary and
     * should not be depended on, but they will always be time-ordered for easy
     * comparison.
     */
    case EDITION_2023 = 1000;
    case EDITION_2024 = 1001;

    /** A placeholder edition for developing and testing unscheduled features. */
    case EDITION_UNSTABLE = 9999;

    /**
     * Placeholder editions for testing feature resolution.  These should not be
     * used or relied on outside of tests.
     */
    case EDITION_1_TEST_ONLY = 1;
    case EDITION_2_TEST_ONLY = 2;
    case EDITION_99997_TEST_ONLY = 99997;
    case EDITION_99998_TEST_ONLY = 99998;
    case EDITION_99999_TEST_ONLY = 99999;

    /**
     * Placeholder for specifying unbounded edition support.  This should only
     * ever be used by plugins that can expect to never require any changes to
     * support a new edition.
     */
    case EDITION_MAX = 2147483647;
}
