<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a value within an enum.
 */
final readonly class EnumValueDescriptorProto
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $number = null,
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\EnumValueOptions::class))]
        public ?\Google\Protobuf\EnumValueOptions $options = null,
    ) {}
}
