<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class EnumValueOptions
{
    /**
     * @param ?bool $deprecated Is this enum value deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for the enum value, or it will be completely ignored; in the very least,
     * this is a formalization for deprecating enum values.
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param ?bool $debugRedact Indicate that fields annotated with this enum value should not be printed
     * out when using debug formats, e.g. when the field contains sensitive
     * credentials.
     * @param ?\Google\Protobuf\FieldOptions\FeatureSupport $featureSupport Information about the support window of a feature value.
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\BoolT::T)]
        public ?bool $deprecated = false,
        #[Reflection\Field(2, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public ?bool $debugRedact = false,
        #[Reflection\Field(4, new Reflection\ObjectT(\Google\Protobuf\FieldOptions\FeatureSupport::class))]
        public ?\Google\Protobuf\FieldOptions\FeatureSupport $featureSupport = null,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
