<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes an enum type.
 */
final readonly class EnumDescriptorProto
{
    /**
     * @param list<\Google\Protobuf\EnumValueDescriptorProto> $value
     * @param list<\Google\Protobuf\EnumDescriptorProto\EnumReservedRange> $reservedRange Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * @param list<string> $reservedName Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * @param ?\Google\Protobuf\SymbolVisibility $visibility Support for `export` and `local` keywords on enums.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\EnumValueDescriptorProto::class), false))]
        public array $value = [],
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\EnumOptions::class))]
        public ?\Google\Protobuf\EnumOptions $options = null,
        #[Reflection\Field(4, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\EnumDescriptorProto\EnumReservedRange::class), false))]
        public array $reservedRange = [],
        #[Reflection\Field(5, new Reflection\ListT(Reflection\StringT::T, false))]
        public array $reservedName = [],
        #[Reflection\Field(6, new Reflection\EnumT(\Google\Protobuf\SymbolVisibility::class))]
        public ?\Google\Protobuf\SymbolVisibility $visibility = null,
    ) {}
}
