<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a value within an enum.
 */
final readonly class EnumValueDescriptorProto
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $number = null,
        #[Reflection\Field(3, new Reflection\ObjectT(\Thesis\Google\Protobuf\EnumValueOptions::class))]
        public ?\Thesis\Google\Protobuf\EnumValueOptions $options = null,
    ) {}
}
