<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class EnumOptions
{
    /**
     * @param ?bool $allowAlias Set this option to true to allow mapping different tag names to the same
     * value.
     * @param ?bool $deprecated Is this enum deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for the enum, or it will be completely ignored; in the very least, this
     * is a formalization for deprecating enums.
     * @param ?bool $deprecatedLegacyJsonFieldConflicts Enable the legacy handling of JSON field name conflicts.  This lowercases
     * and strips underscored from the fields before comparison in proto3 only.
     * The new behavior takes `json_name` into account and applies to proto2 as
     * well.
     * TODO Remove this legacy behavior once downstream teams have
     * had time to migrate.
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     */
    public function __construct(
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public ?bool $allowAlias = null,
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public ?bool $deprecated = false,
        #[Reflection\Field(6, Reflection\BoolT::T)]
        public ?bool $deprecatedLegacyJsonFieldConflicts = null,
        #[Reflection\Field(7, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
