<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ExtensionRangeOptions
{
    /**
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     * @param list<\Google\Protobuf\ExtensionRangeOptions\Declaration> $declaration For external users: DO NOT USE. We are in the process of open sourcing
     * extension declaration and executing internal cleanups before it can be
     * used externally.
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * @param ?\Google\Protobuf\ExtensionRangeOptions\VerificationState $verification The verification state of the range.
     * TODO: flip the default to DECLARATION once all empty ranges
     * are marked as UNVERIFIED.
     */
    public function __construct(
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\ExtensionRangeOptions\Declaration::class), false))]
        public array $declaration = [],
        #[Reflection\Field(50, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(3, new Reflection\EnumT(\Google\Protobuf\ExtensionRangeOptions\VerificationState::class))]
        public ?\Google\Protobuf\ExtensionRangeOptions\VerificationState $verification = null,
    ) {}
}
