<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * TODO Enums in C++ gencode (and potentially other languages) are
 * not well scoped.  This means that each of the feature enums below can clash
 * with each other.  The short names we've chosen maximize call-site
 * readability, but leave us very open to this scenario.  A future feature will
 * be designed and implemented to handle this, hopefully before we ever hit a
 * conflict here.
 */
final readonly class FeatureSet
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Google\Protobuf\FeatureSet\FieldPresence::class))]
        public ?\Google\Protobuf\FeatureSet\FieldPresence $fieldPresence = null,
        #[Reflection\Field(2, new Reflection\EnumT(\Google\Protobuf\FeatureSet\EnumType::class))]
        public ?\Google\Protobuf\FeatureSet\EnumType $enumType = null,
        #[Reflection\Field(3, new Reflection\EnumT(\Google\Protobuf\FeatureSet\RepeatedFieldEncoding::class))]
        public ?\Google\Protobuf\FeatureSet\RepeatedFieldEncoding $repeatedFieldEncoding = null,
        #[Reflection\Field(4, new Reflection\EnumT(\Google\Protobuf\FeatureSet\Utf8Validation::class))]
        public ?\Google\Protobuf\FeatureSet\Utf8Validation $utf8Validation = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Google\Protobuf\FeatureSet\MessageEncoding::class))]
        public ?\Google\Protobuf\FeatureSet\MessageEncoding $messageEncoding = null,
        #[Reflection\Field(6, new Reflection\EnumT(\Google\Protobuf\FeatureSet\JsonFormat::class))]
        public ?\Google\Protobuf\FeatureSet\JsonFormat $jsonFormat = null,
        #[Reflection\Field(7, new Reflection\EnumT(\Google\Protobuf\FeatureSet\EnforceNamingStyle::class))]
        public ?\Google\Protobuf\FeatureSet\EnforceNamingStyle $enforceNamingStyle = null,
        #[Reflection\Field(8, new Reflection\EnumT(\Google\Protobuf\FeatureSet\VisibilityFeature\DefaultSymbolVisibility::class))]
        public ?\Google\Protobuf\FeatureSet\VisibilityFeature\DefaultSymbolVisibility $defaultSymbolVisibility = null,
    ) {}
}
