<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A compiled specification for the defaults of a set of features.  These
 * messages are generated from FeatureSet extensions and can be used to seed
 * feature resolution. The resolution with this object becomes a simple search
 * for the closest matching edition, followed by proto merges.
 */
final readonly class FeatureSetDefaults
{
    /**
     * @param list<\Google\Protobuf\FeatureSetDefaults\FeatureSetEditionDefault> $defaults
     * @param ?\Google\Protobuf\Edition $minimumEdition The minimum supported edition (inclusive) when this was constructed.
     * Editions before this will not have defaults.
     * @param ?\Google\Protobuf\Edition $maximumEdition The maximum known edition (inclusive) when this was constructed. Editions
     * after this will not have reliable defaults.
     */
    public function __construct(
        #[Reflection\Field(
            1,
            new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FeatureSetDefaults\FeatureSetEditionDefault::class), false),
        )]
        public array $defaults = [],
        #[Reflection\Field(4, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $minimumEdition = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $maximumEdition = null,
    ) {}
}
