<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class FieldOptions
{
    /**
     * @param ?\Google\Protobuf\FieldOptions\CType $ctype NOTE: ctype is deprecated. Use `features.(pb.cpp).string_type` instead.
     * The ctype option instructs the C++ code generator to use a different
     * representation of the field than it normally would.  See the specific
     * options below.  This option is only implemented to support use of
     * [ctype=CORD] and [ctype=STRING] (the default) on non-repeated fields of
     * type "bytes" in the open source release.
     * TODO: make ctype actually deprecated.
     * @param ?bool $packed The packed option can be enabled for repeated primitive fields to enable
     * a more efficient representation on the wire. Rather than repeatedly
     * writing the tag and type for each element, the entire array is encoded as
     * a single length-delimited blob. In proto3, only explicit setting it to
     * false will avoid using packed encoding.  This option is prohibited in
     * Editions, but the `repeated_field_encoding` feature can be used to control
     * the behavior.
     * @param ?\Google\Protobuf\FieldOptions\JSType $jstype The jstype option determines the JavaScript type used for values of the
     * field.  The option is permitted only for 64 bit integral and fixed types
     * (int64, uint64, sint64, fixed64, sfixed64).  A field with jstype JS_STRING
     * is represented as JavaScript string, which avoids loss of precision that
     * can happen when a large value is converted to a floating point JavaScript.
     * Specifying JS_NUMBER for the jstype causes the generated JavaScript code to
     * use the JavaScript "number" type.  The behavior of the default option
     * JS_NORMAL is implementation dependent.
     *
     * This option is an enum to permit additional types to be added, e.g.
     * goog.math.Integer.
     * @param ?bool $lazy Should this field be parsed lazily?  Lazy applies only to message-type
     * fields.  It means that when the outer message is initially parsed, the
     * inner message's contents will not be parsed but instead stored in encoded
     * form.  The inner message will actually be parsed when it is first accessed.
     *
     * This is only a hint.  Implementations are free to choose whether to use
     * eager or lazy parsing regardless of the value of this option.  However,
     * setting this option true suggests that the protocol author believes that
     * using lazy parsing on this field is worth the additional bookkeeping
     * overhead typically needed to implement it.
     *
     * This option does not affect the public interface of any generated code;
     * all method signatures remain the same.  Furthermore, thread-safety of the
     * interface is not affected by this option; const methods remain safe to
     * call from multiple threads concurrently, while non-const methods continue
     * to require exclusive access.
     *
     * Note that lazy message fields are still eagerly verified to check
     * ill-formed wireformat or missing required fields. Calling IsInitialized()
     * on the outer message would fail if the inner message has missing required
     * fields. Failed verification would result in parsing failure (except when
     * uninitialized messages are acceptable).
     * @param ?bool $unverifiedLazy unverified_lazy does no correctness checks on the byte stream. This should
     * only be used where lazy with verification is prohibitive for performance
     * reasons.
     * @param ?bool $deprecated Is this field deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for accessors, or it will be completely ignored; in the very least, this
     * is a formalization for deprecating fields.
     * @param ?bool $weak DEPRECATED. DO NOT USE!
     * For Google-internal migration only. Do not use.
     * @param ?bool $debugRedact Indicate that the field value should not be printed out when using debug
     * formats, e.g. when the field contains sensitive credentials.
     * @param list<\Google\Protobuf\FieldOptions\OptionTargetType> $targets
     * @param list<\Google\Protobuf\FieldOptions\EditionDefault> $editionDefaults
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\EnumT(\Google\Protobuf\FieldOptions\CType::class))]
        public ?\Google\Protobuf\FieldOptions\CType $ctype = null,
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public ?bool $packed = null,
        #[Reflection\Field(6, new Reflection\EnumT(\Google\Protobuf\FieldOptions\JSType::class))]
        public ?\Google\Protobuf\FieldOptions\JSType $jstype = null,
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public ?bool $lazy = false,
        #[Reflection\Field(15, Reflection\BoolT::T)]
        public ?bool $unverifiedLazy = false,
        #[Reflection\Field(3, Reflection\BoolT::T)]
        public ?bool $deprecated = false,
        #[Reflection\Field(10, Reflection\BoolT::T)]
        public ?bool $weak = false,
        #[Reflection\Field(16, Reflection\BoolT::T)]
        public ?bool $debugRedact = false,
        #[Reflection\Field(17, new Reflection\EnumT(\Google\Protobuf\FieldOptions\OptionRetention::class))]
        public ?\Google\Protobuf\FieldOptions\OptionRetention $retention = null,
        #[Reflection\Field(19, new Reflection\ListT(new Reflection\EnumT(\Google\Protobuf\FieldOptions\OptionTargetType::class), false))]
        public array $targets = [],
        #[Reflection\Field(20, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FieldOptions\EditionDefault::class), false))]
        public array $editionDefaults = [],
        #[Reflection\Field(21, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(22, new Reflection\ObjectT(\Google\Protobuf\FieldOptions\FeatureSupport::class))]
        public ?\Google\Protobuf\FieldOptions\FeatureSupport $featureSupport = null,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
