<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a field within a message.
 */
final readonly class FieldDescriptorProto
{
    /**
     * @param ?\Google\Protobuf\FieldDescriptorProto\Type $type If type_name is set, this need not be set.  If both this and type_name
     * are set, this must be one of TYPE_ENUM, TYPE_MESSAGE or TYPE_GROUP.
     * @param ?string $typeName For message and enum types, this is the name of the type.  If the name
     * starts with a '.', it is fully-qualified.  Otherwise, C++-like scoping
     * rules are used to find the type (i.e. first the nested types within this
     * message are searched, then within the parent, on up to the root
     * namespace).
     * @param ?string $extendee For extensions, this is the name of the type being extended.  It is
     * resolved in the same manner as type_name.
     * @param ?string $defaultValue For numeric types, contains the original text representation of the value.
     * For booleans, "true" or "false".
     * For strings, contains the default text contents (not escaped in any way).
     * For bytes, contains the C escaped value.  All bytes >= 128 are escaped.
     * @param ?int $oneofIndex If set, gives the index of a oneof in the containing type's oneof_decl
     * list.  This field is a member of that oneof.
     * @param ?string $jsonName JSON name of this field. The value is set by protocol compiler. If the
     * user has set a "json_name" option on this field, that option's value
     * will be used. Otherwise, it's deduced from the field's name by converting
     * it to camelCase.
     * @param ?bool $proto3Optional If true, this is a proto3 "optional". When a proto3 field is optional, it
     * tracks presence regardless of field type.
     *
     * When proto3_optional is true, this field must belong to a oneof to signal
     * to old proto3 clients that presence is tracked for this field. This oneof
     * is known as a "synthetic" oneof, and this field must be its sole member
     * (each proto3 optional field gets its own synthetic oneof). Synthetic oneofs
     * exist in the descriptor only, and do not generate any API. Synthetic oneofs
     * must be ordered after all "real" oneofs.
     *
     * For message fields, proto3_optional doesn't create any semantic change,
     * since non-repeated message fields always track presence. However it still
     * indicates the semantic detail of whether the user wrote "optional" or not.
     * This can be useful for round-tripping the .proto file. For consistency we
     * give message fields a synthetic oneof also, even though it is not required
     * to track presence. This is especially important because the parser can't
     * tell if a field is a message or an enum, so it must always create a
     * synthetic oneof.
     *
     * Proto2 optional fields do not set this flag, because they already indicate
     * optional with `LABEL_OPTIONAL`.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public ?int $number = null,
        #[Reflection\Field(4, new Reflection\EnumT(\Google\Protobuf\FieldDescriptorProto\Label::class))]
        public ?\Google\Protobuf\FieldDescriptorProto\Label $label = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Google\Protobuf\FieldDescriptorProto\Type::class))]
        public ?\Google\Protobuf\FieldDescriptorProto\Type $type = null,
        #[Reflection\Field(6, Reflection\StringT::T)]
        public ?string $typeName = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $extendee = null,
        #[Reflection\Field(7, Reflection\StringT::T)]
        public ?string $defaultValue = null,
        #[Reflection\Field(9, Reflection\Int32T::T)]
        public ?int $oneofIndex = null,
        #[Reflection\Field(10, Reflection\StringT::T)]
        public ?string $jsonName = null,
        #[Reflection\Field(8, new Reflection\ObjectT(\Google\Protobuf\FieldOptions::class))]
        public ?\Google\Protobuf\FieldOptions $options = null,
        #[Reflection\Field(17, Reflection\BoolT::T)]
        public ?bool $proto3Optional = null,
    ) {}
}
