<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class FileOptions
{
    /**
     * @param ?string $javaPackage Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * @param ?string $javaOuterClassname Controls the name of the wrapper Java class generated for the .proto file.
     * That class will always contain the .proto file's getDescriptor() method as
     * well as any top-level extensions defined in the .proto file.
     * If java_multiple_files is disabled, then all the other classes from the
     * .proto file will be nested inside the single wrapper outer class.
     * @param ?bool $javaMultipleFiles If enabled, then the Java code generator will generate a separate .java
     * file for each top-level message, enum, and service defined in the .proto
     * file.  Thus, these types will *not* be nested inside the wrapper class
     * named by java_outer_classname.  However, the wrapper class will still be
     * generated to contain the file's getDescriptor() method as well as any
     * top-level extensions defined in the file.
     * @param ?bool $javaGenerateEqualsAndHash This option does nothing.
     * @param ?bool $javaStringCheckUtf8 A proto2 file can set this to true to opt in to UTF-8 checking for Java,
     * which will throw an exception if invalid UTF-8 is parsed from the wire or
     * assigned to a string field.
     *
     * TODO: clarify exactly what kinds of field types this option
     * applies to, and update these docs accordingly.
     *
     * Proto3 files already perform these checks. Setting the option explicitly to
     * false has no effect: it cannot be used to opt proto3 files out of UTF-8
     * checks.
     * @param ?string $goPackage Sets the Go package where structs generated from this .proto will be
     * placed. If omitted, the Go package will be derived from the following:
     *   - The basename of the package import path, if provided.
     *   - Otherwise, the package statement in the .proto file, if present.
     *   - Otherwise, the basename of the .proto file, without extension.
     * @param ?bool $ccGenericServices Should generic services be generated in each language?  "Generic" services
     * are not specific to any particular RPC system.  They are generated by the
     * main code generators in each language (without additional plugins).
     * Generic services were the only kind of service generation supported by
     * early versions of google.protobuf.
     *
     * Generic services are now considered deprecated in favor of using plugins
     * that generate code specific to your particular RPC system.  Therefore,
     * these default to false.  Old code which depends on generic services should
     * explicitly set them to true.
     * @param ?bool $deprecated Is this file deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for everything in the file, or it will be completely ignored; in the very
     * least, this is a formalization for deprecating files.
     * @param ?bool $ccEnableArenas Enables the use of arenas for the proto messages in this file. This applies
     * only to generated classes for C++.
     * @param ?string $objcClassPrefix Sets the objective c class prefix which is prepended to all objective c
     * generated classes from this .proto. There is no default.
     * @param ?string $csharpNamespace Namespace for generated classes; defaults to the package.
     * @param ?string $swiftPrefix By default Swift generators will take the proto package and CamelCase it
     * replacing '.' with underscore and use that to prefix the types/symbols
     * defined. When this options is provided, they will use this value instead
     * to prefix the types/symbols defined.
     * @param ?string $phpClassPrefix Sets the php class prefix which is prepended to all php generated classes
     * from this .proto. Default is empty.
     * @param ?string $phpNamespace Use this option to change the namespace of php generated classes. Default
     * is empty. When this option is empty, the package name will be used for
     * determining the namespace.
     * @param ?string $phpMetadataNamespace Use this option to change the namespace of php generated metadata classes.
     * Default is empty. When this option is empty, the proto file name will be
     * used for determining the namespace.
     * @param ?string $rubyPackage Use this option to change the package of ruby generated classes. Default
     * is empty. When this option is not set, the package name will be used for
     * determining the ruby package.
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here.
     * See the documentation for the "Options" section above.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $javaPackage = null,
        #[Reflection\Field(8, Reflection\StringT::T)]
        public ?string $javaOuterClassname = null,
        #[Reflection\Field(10, Reflection\BoolT::T)]
        public ?bool $javaMultipleFiles = false,
        #[Reflection\Field(20, Reflection\BoolT::T)]
        public ?bool $javaGenerateEqualsAndHash = null,
        #[Reflection\Field(27, Reflection\BoolT::T)]
        public ?bool $javaStringCheckUtf8 = false,
        #[Reflection\Field(9, new Reflection\EnumT(\Google\Protobuf\FileOptions\OptimizeMode::class))]
        public ?\Google\Protobuf\FileOptions\OptimizeMode $optimizeFor = null,
        #[Reflection\Field(11, Reflection\StringT::T)]
        public ?string $goPackage = null,
        #[Reflection\Field(16, Reflection\BoolT::T)]
        public ?bool $ccGenericServices = false,
        #[Reflection\Field(17, Reflection\BoolT::T)]
        public ?bool $javaGenericServices = false,
        #[Reflection\Field(18, Reflection\BoolT::T)]
        public ?bool $pyGenericServices = false,
        #[Reflection\Field(23, Reflection\BoolT::T)]
        public ?bool $deprecated = false,
        #[Reflection\Field(31, Reflection\BoolT::T)]
        public ?bool $ccEnableArenas = true,
        #[Reflection\Field(36, Reflection\StringT::T)]
        public ?string $objcClassPrefix = null,
        #[Reflection\Field(37, Reflection\StringT::T)]
        public ?string $csharpNamespace = null,
        #[Reflection\Field(39, Reflection\StringT::T)]
        public ?string $swiftPrefix = null,
        #[Reflection\Field(40, Reflection\StringT::T)]
        public ?string $phpClassPrefix = null,
        #[Reflection\Field(41, Reflection\StringT::T)]
        public ?string $phpNamespace = null,
        #[Reflection\Field(44, Reflection\StringT::T)]
        public ?string $phpMetadataNamespace = null,
        #[Reflection\Field(45, Reflection\StringT::T)]
        public ?string $rubyPackage = null,
        #[Reflection\Field(50, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
