<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The protocol compiler can output a FileDescriptorSet containing the .proto
 * files it parses.
 */
final readonly class FileDescriptorSet
{
    /**
     * @param list<\Google\Protobuf\FileDescriptorProto> $file
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FileDescriptorProto::class), false))]
        public array $file = [],
    ) {}
}
