<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a complete .proto file.
 */
final readonly class FileDescriptorProto
{
    /**
     * @param ?string $name file name, relative to root of source tree
     * @param ?string $package e.g. "foo", "foo.bar", etc.
     * @param list<string> $dependency Names of files imported by this file.
     * @param list<int> $publicDependency Indexes of the public imported files in the dependency list above.
     * @param list<int> $weakDependency Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * @param list<string> $optionDependency Names of files imported by this file purely for the purpose of providing
     * option extensions. These are excluded from the dependency list above.
     * @param list<\Google\Protobuf\DescriptorProto> $messageType All top-level definitions in this file.
     * @param list<\Google\Protobuf\EnumDescriptorProto> $enumType
     * @param list<\Google\Protobuf\ServiceDescriptorProto> $service
     * @param list<\Google\Protobuf\FieldDescriptorProto> $extension
     * @param ?\Google\Protobuf\SourceCodeInfo $sourceCodeInfo This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     * @param ?string $syntax The syntax of the proto file.
     * The supported values are "proto2", "proto3", and "editions".
     *
     * If `edition` is present, this value must be "editions".
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param ?\Google\Protobuf\Edition $edition The edition of the proto file.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $package = null,
        #[Reflection\Field(3, new Reflection\ListT(Reflection\StringT::T, false))]
        public array $dependency = [],
        #[Reflection\Field(10, new Reflection\ListT(Reflection\Int32T::T, false))]
        public array $publicDependency = [],
        #[Reflection\Field(11, new Reflection\ListT(Reflection\Int32T::T, false))]
        public array $weakDependency = [],
        #[Reflection\Field(15, new Reflection\ListT(Reflection\StringT::T, false))]
        public array $optionDependency = [],
        #[Reflection\Field(4, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\DescriptorProto::class), false))]
        public array $messageType = [],
        #[Reflection\Field(5, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\EnumDescriptorProto::class), false))]
        public array $enumType = [],
        #[Reflection\Field(6, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\ServiceDescriptorProto::class), false))]
        public array $service = [],
        #[Reflection\Field(7, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FieldDescriptorProto::class), false))]
        public array $extension = [],
        #[Reflection\Field(8, new Reflection\ObjectT(\Google\Protobuf\FileOptions::class))]
        public ?\Google\Protobuf\FileOptions $options = null,
        #[Reflection\Field(9, new Reflection\ObjectT(\Google\Protobuf\SourceCodeInfo::class))]
        public ?\Google\Protobuf\SourceCodeInfo $sourceCodeInfo = null,
        #[Reflection\Field(12, Reflection\StringT::T)]
        public ?string $syntax = null,
        #[Reflection\Field(14, new Reflection\EnumT(\Google\Protobuf\Edition::class))]
        public ?\Google\Protobuf\Edition $edition = null,
    ) {}
}
