<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes the relationship between generated code and its original source
 * file. A GeneratedCodeInfo message is associated with only one generated
 * source file, but may contain references to different source .proto files.
 */
final readonly class GeneratedCodeInfo
{
    /**
     * @param list<\Google\Protobuf\GeneratedCodeInfo\Annotation> $annotation An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\GeneratedCodeInfo\Annotation::class), false))]
        public array $annotation = [],
    ) {}
}
