<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a method of a service.
 */
final readonly class MethodDescriptorProto
{
    /**
     * @param ?string $inputType Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     * @param ?bool $clientStreaming Identifies if client streams multiple client messages
     * @param ?bool $serverStreaming Identifies if server streams multiple server messages
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $inputType = null,
        #[Reflection\Field(3, Reflection\StringT::T)]
        public ?string $outputType = null,
        #[Reflection\Field(4, new Reflection\ObjectT(\Google\Protobuf\MethodOptions::class))]
        public ?\Google\Protobuf\MethodOptions $options = null,
        #[Reflection\Field(5, Reflection\BoolT::T)]
        public ?bool $clientStreaming = false,
        #[Reflection\Field(6, Reflection\BoolT::T)]
        public ?bool $serverStreaming = false,
    ) {}
}
