<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class OneofOptions
{
    /**
     * @param ?\Thesis\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param list<\Thesis\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Thesis\Google\Protobuf\FeatureSet::class))]
        public ?\Thesis\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Thesis\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
