<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Describes a service.
 */
final readonly class ServiceDescriptorProto
{
    /**
     * @param list<\Google\Protobuf\MethodDescriptorProto> $method
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\MethodDescriptorProto::class), false))]
        public array $method = [],
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\ServiceOptions::class))]
        public ?\Google\Protobuf\ServiceOptions $options = null,
    ) {}
}
