<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ServiceOptions
{
    /**
     * @param ?\Google\Protobuf\FeatureSet $features Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     * @param ?bool $deprecated Is this service deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for the service, or it will be completely ignored; in the very least,
     * this is a formalization for deprecating services.
     * @param list<\Google\Protobuf\UninterpretedOption> $uninterpretedOption The parser stores options it doesn't recognize here. See above.
     */
    public function __construct(
        #[Reflection\Field(34, new Reflection\ObjectT(\Google\Protobuf\FeatureSet::class))]
        public ?\Google\Protobuf\FeatureSet $features = null,
        #[Reflection\Field(33, Reflection\BoolT::T)]
        public ?bool $deprecated = false,
        #[Reflection\Field(999, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption::class), false))]
        public array $uninterpretedOption = [],
    ) {}
}
