<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.5
 *   protoc               — v6.33.5
 * Source: google/protobuf/descriptor.proto
 */

declare(strict_types=1);

namespace Google\Protobuf;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A message representing a option the parser does not recognize. This only
 * appears in options protos created by the compiler::Parser class.
 * DescriptorPool resolves these when building Descriptor objects. Therefore,
 * options protos in descriptor objects (e.g. returned by Descriptor::options(),
 * or produced by Descriptor::CopyTo()) will never have UninterpretedOptions
 * in them.
 */
final readonly class UninterpretedOption
{
    /**
     * @param list<\Google\Protobuf\UninterpretedOption\NamePart> $name
     * @param ?string $identifierValue The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     */
    public function __construct(
        #[Reflection\Field(2, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\UninterpretedOption\NamePart::class), false))]
        public array $name = [],
        #[Reflection\Field(3, Reflection\StringT::T)]
        public ?string $identifierValue = null,
        #[Reflection\Field(4, Reflection\Uint64T::T)]
        public ?\BcMath\Number $positiveIntValue = null,
        #[Reflection\Field(5, Reflection\Int64T::T)]
        public ?\BcMath\Number $negativeIntValue = null,
        #[Reflection\Field(6, Reflection\DoubleT::T)]
        public ?float $doubleValue = null,
        #[Reflection\Field(7, Reflection\BytesT::T)]
        public ?string $stringValue = null,
        #[Reflection\Field(8, Reflection\StringT::T)]
        public ?string $aggregateValue = null,
    ) {}
}
